<div class="row">
    <div class="col-md-12">
        <form class="form-inline">
            <div class="form-group">
                <input type="text" name="phrase" class="form-control" placeholder="Fraza" value="<?=$this->phrase ?>" />
            </div>
            <input type="submit" name="search" value="Szukaj" class="btn btn-primary" />
        </form>
    </div>
</div>
<?php if (!empty($ekspozycja)): ?>
<?php foreach ($ekspozycja->photo as $p): ?>
<?php $src = "https://live.staticflickr.com/" . $p->server . "/" . $p->id . "_" . $p->secret . ".jpg";
        if (isset($p->originalformat)) {
            $format = $p->originalformat;
            $original = "https://live.staticflickr.com/" . $p->server . "/" . $p->id . "_" . $p->originalsecret . "_o." . $format;
        }else{
            $original = $src;
        }
?>
    <a href=<?= $original?>><img src=<?= $src ?> class="img-thumbnail" class="rounded float-left"></a>
<?php endforeach; ?>
<?php endif; ?>